# Generated by Django 4.2.6 on 2023-10-31 09:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_floodedimage_prediction_data_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodedimage',
            name='coordinates',
        ),
        migrations.RemoveField(
            model_name='floodedimage',
            name='title',
        ),
        migrations.AlterField(
            model_name='floodedimage',
            name='segmented_image',
            field=models.TextField(),
        ),
    ]
