# Generated by Django 4.2.6 on 2023-11-04 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_alter_floodedimage_prediction_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='floodedimage',
            name='segmented_image',
        ),
    ]
