# Generated by Django 4.2.6 on 2023-11-11 12:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('home', '0008_floodedimage_segmented_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='floodedimage',
            name='segmented_image',
            field=models.ImageField(default=None, upload_to='mask'),
        ),
        migrations.CreateModel(
            name='FloodedImagePatch',
            fields=[
                ('uid', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now_add=True)),
                ('patch_code', models.CharField(default='', max_length=100)),
                ('image_id', models.CharField(default='', max_length=100)),
                ('captured_image', models.ImageField(upload_to='image')),
                ('segmented_image', models.ImageField(default=None, upload_to='mask')),
                ('prediction_data', models.JSONField(default=dict)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='FloodedImagePatch', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
